//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Management_system.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee
    {
        public int Id { get; set; }
        [Required (ErrorMessage ="Required")]
        public string Firstname { get; set; }
        [Required(ErrorMessage = "Required")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Required")]
        [EmailAddress]
        public string Email { get; set; }
        [Required(ErrorMessage = "Required")]
        public string phone { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Position { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<decimal> Salary { get; set; }
    }
}
